name: Azure Static Web Apps and Azure App Services CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**' # Trigger only when files in the frontend directory are changed
      - 'backend/**'  # Trigger only when files in the backend directory are changed
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
  workflow_dispatch:

jobs:
  # Frontend job (build and deploy only if changes are in the frontend directory)
  build_and_deploy_frontend:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build and Deploy Frontend
        id: builddeployfrontend
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_DESERT_0A59D0B03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e., PR comments)
          action: "upload"
          app_location: "./frontend" # App source code path
          api_location: "" # API source code path - optional
          output_location: "build" # Built app content directory - optional
        env:
          REACT_APP_AUTH_CLIENT_ID: ${{ secrets.REACT_APP_AUTH_CLIENT_ID }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

  # Backend job (deploy only if changes are in the backend directory)
  deploy_backend:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: windows-latest
    name: Deploy Backend
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version for backend
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Build backend
        run: |
          cd backend
          npm run build

      # Add a step to create a ZIP package of the backend
      - name: Package backend for deployment
        run: |
          cd backend
          zip -r ../backend.zip . 

      # Azure Login with Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Secret containing the service principal credentials

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Lagunabutchery'
          package: ./backend.zip # Use the zip file created earlier