name: Azure Static Web Apps and Azure App Services CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_frontend:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build and Deploy Frontend
        id: builddeployfrontend
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_DESERT_0A59D0B03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "./frontend" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_DESERT_0A59D0B03 }}
          action: "close"

  build_backend:
    runs-on: windows-latest
    name: Build Backend
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version for backend
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and fix vulnerabilities
        run: |
          cd backend
          npm install
          npm audit fix || true

      - name: Run backend build
        run: |
          cd backend
          npm run build --if-present
      
      - name: Upload backend artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: "./backend"

  deploy_backend:
    runs-on: ubuntu-latest
    needs: build_backend
    name: Deploy Backend
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4D1451B762A34ACF978257DD0530D49C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_94B8BE88EC8A4EE69616A5D6BE34A139 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9758212CADDF4E4496BC302D2D9EB1A3 }}

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Lagunabutchery'
          slot-name: 'Production'
          package: './backend'