name: Azure Static Web Apps and Azure App Services CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
  workflow_dispatch:

jobs:
  # Frontend job (build and deploy only if changes are in the frontend directory)
  build_and_deploy_frontend:
    if: contains(github.event.head_commit.message, 'frontend')
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Build and Deploy Frontend
        id: builddeployfrontend
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_DESERT_0A59D0B03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./frontend"  # App source code path
          api_location: ""  # API source code path - optional
          output_location: "build"  # Built app content directory - optional
        env:
          REACT_APP_AUTH_CLIENT_ID: ${{ secrets.REACT_APP_AUTH_CLIENT_ID }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

  build_and_deploy_backend:
      if: contains(github.event.head_commit.message, 'backend')
      runs-on: ubuntu-latest
      name: Build and Deploy Backend
      steps:
        - name: Checkout Source
          uses: actions/checkout@master

        - name: Setup Node.js version
          uses: actions/setup-node@v4
          with:
              node-version: '20.x'

        - name: Install Dependencies
          run: |
            cd backend  
            npm install

        - name: Deploy to Azure App Service
          uses: azure/webapps-deploy@v2
          with:
            app-name: lagunabutchery
            publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
            package: .
