name: Azure Static Web Apps and Azure App Services CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'  # Trigger only when files in the frontend directory are changed
      - 'backend/**'   # Trigger only when files in the backend directory are changed
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
  workflow_dispatch:

jobs:
  # Frontend job (build and deploy only if changes are in the frontend directory)
  build_and_deploy_frontend:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Build and Deploy Frontend
        id: builddeployfrontend
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_DESERT_0A59D0B03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Used for GitHub integrations (i.e., PR comments)
          action: "upload"
          app_location: "./frontend"  # App source code path
          api_location: ""  # API source code path - optional
          output_location: "build"  # Built app content directory - optional
        env:
          REACT_APP_AUTH_CLIENT_ID: ${{ secrets.REACT_APP_AUTH_CLIENT_ID }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

  # Backend job (build and deploy only if changes are in the backend directory)
  build_and_deploy_backend:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'  # Point to the lock file in the backend folder

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Build backend
        run: |
          cd backend
          npm run build --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: backend  # Ensure this path is correct

  deploy_backend:
    runs-on: ubuntu-latest
    needs: build_and_deploy_backend
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-app

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Lagunabutchery'
          package: backend  # Path to the backend folder where the code exists